//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eduketa_Proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoCourse
    {
        public int id { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string course { get; set; }
        public Nullable<System.DateTime> demodate { get; set; }
        public Nullable<System.TimeSpan> demotime { get; set; }
    }
}
