//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eduketa_Proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public int id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string email_add { get; set; }
        public string mobile_no { get; set; }
        public string social_prof { get; set; }
        public string password { get; set; }
        public string company_name { get; set; }
    }
}
